#makefile for 229 Project 2 game of life prototype

#compiler to use
CC=g++

#all executables
ALL=life lifegui

#executables
#TODO

#object files
Simulation.o: Simulation.cc Simulation.hh
	$(CC) -c Simulation.cc

#clean
clean:
	rm -f $(ALL) *.o

cleanobjects:
	rm -f *.o
